/* Containment Breach — the word bank.
 *
 * GENERATED by tools/build-wordbank.js. Do not hand-edit: edit the stem lists
 * in that script and regenerate, so that every word stays dictionary-verified.
 *
 * Words are mined from an English dictionary by thematic stem rather than
 * written out by hand. Hand-writing a bank this size is how the previous one
 * ended up shipping "putri" and "outbrek" — truncations that looked like words
 * at a glance and were impossible to type from sight. Every entry below was
 * checked against the dictionary at build time.
 *
 * Buckets are by length, which is what the difficulty curve selects on.
 */
(function (global) {
  'use strict';
  var CT = (global.ContainmentBreach = global.ContainmentBreach || {});

  var BY_LENGTH = {};

  BY_LENGTH[3] = (
    "ail arm ash bat bio bug cog cry cut den " +
    "dim dry dye ear ebb eye fat fog fur gag " +
    "gas gel gum gut hex hip hit hum ice ion " +
    "jab jar jaw lab lid mar maw mud nap orb " +
    "ore pen pit ply pod pox pry pup pus rat " +
    "raw rib rig rim rip rot rub rug run rut " +
    "sac sag sap sob sod sow tag tar toe tow " +
    "tug vat vet vex vow wan wax web wet wit " +
    "woe wry"
  ).split(' ');

  BY_LENGTH[4] = (
    "ache acid axon bald bane bile biog bion bite blot " +
    "boil bolt bone brow bulk burn cage cane cast cave " +
    "cell char chew clan claw clog clot coil cold crag " +
    "cyst damp dank dark dart daze dent derm dire dirt " +
    "door dose drab drag dram drip duct dull dusk dust " +
    "echo edge etch fade fail fake fall fang fear fell " +
    "fern file fill film flap flay fled flee flex flog " +
    "flux foam foil fold fume fuse gale gall gape gash " +
    "gasp gaze gene germ gill girt glow glut gnat gnaw " +
    "gore gout grab gram grid grim grip grit grow gulf " +
    "gust hack hail halt hare harm haul hazy heap heat " +
    "heed herd hide hilt hind hive hole hood hook horn " +
    "host howl hulk hunt hurl hurt husk idle inch itch " +
    "jolt keen kelp kiln knit knob knot lace lair lame " +
    "lamp lard lash leak leap lick limb lime limp lisp " +
    "loam lobe lock lode loom loop lore lost lump lung " +
    "lure lurk lush mare mash mask mass mast mate maul " +
    "maze mead meal mean meat mend mesh mess mica mild " +
    "mine mire mist mite moan moat mock mold mole molt " +
    "monk mood moor mope moss moth muck mull murk mush " +
    "musk mute myth nail name nape nave neat neck need " +
    "nest nick node norm nose nova numb oath odor omen " +
    "onus ooze opal oust oval oven over pact pail pain " +
    "pale pall palm pane pang pant pare park pass past " +
    "pate path pawn peak peal peat peck peel peer pelt " +
    "pest pick pier pike pile pill pine pipe pith pity " +
    "plan plea pled plod plot poke pole poll pond pool " +
    "pore pork port pose post pour prey prod prop pull " +
    "pulp pump pure push pyre quiz raft rage raid rail " +
    "rake ramp rank rant rash rasp rate rave raze reap " +
    "rear reed reef reek reel rein rend rent rest rice " +
    "rife rind ring riot rise risk rite roam roar robe " +
    "rock rode roil role roll romp roof room root rope " +
    "rose rove rude ruin rule rung runt ruse rush rust " +
    "sack sage sail salt sand sane sash save scab scan " +
    "scar scum seal seam sear seat sect seed seek seep " +
    "serf shed shin shun shut sick sift sigh sign silo " +
    "silt sink skew skid skin slab slag slam slap sled " +
    "slip slit slot slow slug slur snag snap soak soar " +
    "soil soot sore sour span spew spin spur stab stag " +
    "stem step stew stir stop stub stud stun suck sulk " +
    "sump surg swab sway tack tame tang tank tarn taut " +
    "teem tend term thaw thin thud tide tilt tint tire " +
    "toil toll tomb tone tong tool torn toss trap trim " +
    "trip true tube tuck turf turn tusk twig undo unit " +
    "urge vain vale vamp vane veer veil vein vend vent " +
    "vial vibe vice view vile vine void volt wade waft " +
    "wage wail wake wall wane ward warn warp wary wave " +
    "weak wean wear weed week weep weir weld welt whet " +
    "whim whip wild wilt wind wing wink wipe wire wisp " +
    "wolf womb wood wool word work worm worn wrap writ " +
    "yank yard yarn yawn year yell yelp yoke yolk zeal " +
    "zone"
  ).split(' ');

  BY_LENGTH[5] = (
    "amino arend arter assay biota blast chasm chlor colon crawl " +
    "creak creep cytol decay derma dosis dread drone dwell edema " +
    "endow ethyl feral fetal fetid fungi fungo genet genic genom " +
    "gloom gnash grate grave greed growl harsh haunt hissy hunch " +
    "hydro inert karst kendo lance lapse latch lathe ledge leech " +
    "lever linen lipid lithe loath lunge lymph lysis lysol lytic " +
    "mange mania marsh moist motor mount mourn murky mycol myoma " +
    "necro nerve nitro noose notch oaken ology organ pathy pearl " +
    "perch peril phage phase plait plasm plate pluck plumb plume " +
    "plump pouch pound prank press prick pride prime print prism " +
    "probe prong proof prose prowl prune pulse punch purge quail " +
    "quake qualm quart quell quest queue quill quilt quirk rabid " +
    "reign relic rendu retin ridge rinse rival roast rough round " +
    "rouse saxon scald scale scalp scent scold scoop scope score " +
    "scorn scour scowl scrap screw scrub sedat seize sense sepal " +
    "serum sever shade shaft shake shale shall shame shank shape " +
    "shard shave shear sheen sheer shelf shell shift shine shirk " +
    "shoal shock shoot shore short shove shred shrub sinew singe " +
    "sinus siren skirt skulk slack slake slant slash slate slave " +
    "sleek sleet slice slick slide slime slope slump smear smelt " +
    "smite smoke snare snarl sneer sniff snout sound spade spare " +
    "spark spasm spawn speck speed spell spend spent spike spill " +
    "spire spite split spoil spoke spool spore spray sprig spurn " +
    "spurt squat stack stain stair stake stale stalk stall stamp " +
    "stand stark start stash state stave stead steam steel steep " +
    "steer stern stick stiff still sting stink stock stoke stone " +
    "stoop store storm stout stove strap straw stray strew strip " +
    "stump stunt sulfa surge swamp swarm swath swear sweat sweep " +
    "swell swift swill swine swirl swoop sword taint talon taper " +
    "taxon tempt tendo tense tepid terse thick thief thorn throb " +
    "thump tinge tissu token tooth torch torso tough toxic toxin " +
    "trace track tract trail train trait tramp trash tread treat " +
    "trend trial tribe trick troll troop trout truce truck trunk " +
    "trust truth twine twist ulcer umber uncle unfit untie upend " +
    "usher usual utter vague valve vapor vault velum venom verge " +
    "verse vigil viper viral virus visor vital vivid vocal vomit " +
    "vouch waist waste watch water weave wedge weigh wench whack " +
    "whale wharf wheel whelp whiff while whine whirl whisk wield " +
    "wince winch withe worry worse worth wound wrath wreak wreck " +
    "wrest wring wrist wrong yeast yield zendo"
  ).split(' ');

  BY_LENGTH[6] = (
    "abrash acidic alkali analyt anemia anemic anomal apathy artery axonal " +
    "barter basalt benign berend biogas bionic biopsy biosis biotic biotin " +
    "breach brenda buffer burrow camino carbon cardia cardin carter cavern " +
    "chasma chloro chromo clinic colony corpse costal creepy cretin daimyo " +
    "darter dermal devour dilute embryo engulf enzyme excise exhume fathom " +
    "fester foetal frenzy fright fungal fungus gabion garter genome gloomy " +
    "gnosis grotto gypsum hollow horror hydrol incise infect infuse inject " +
    "ionize iritis klaxon lesion lethal lumber lurker malady malign marrow " +
    "mauler methyl morbid morgan morgue mutate myelin myopia myopic myosin " +
    "neural neurol neuron nitric nuclei oblast ocular oedema oocyte opaque " +
    "orenda organa otitis oxygen parter pathol pelvic pewter philia phobia " +
    "plasma plunge poison pounce premia ptosis putrid quarry redact reflex " +
    "remedy render retina ribose savage saxony scorch scrape scrawl scream " +
    "scribe scroll secret sedate sepsis septic shadow sheath shield shrewd " +
    "shriek shrill shrine shrink shroud sinewy siphon slight sludge spinal " +
    "splash splice sprawl spread spring sprout squall squeal squirm starve " +
    "stench strain strait strand streak stream strict stride strife strike " +
    "string strive stroke strong struck sturdy suffer sulfur sullen sunder " +
    "surger suture swerve switch tangle tarter tendon terror thrash thread " +
    "threat thresh thrive throat throng thrust tibial timber tissue topple " +
    "toxine trance trauma tremor trench trendy trophy trough trudge tumble " +
    "tundra tunnel twitch uremia ureter vendor venous vessel viable vortex " +
    "vulgar wander wither wonder wrench wretch writhe"
  ).split(' ');

  BY_LENGTH[7] = (
    "abandon abscess abyssal abysses adrenal agonist agonize ailment airlock alveoli " +
    "ammonia amputee anaemia anaemic anguish anomala antigen aplasia aqueous aquifer " +
    "artemia arteria asepsis aseptic assayer atrophy autopsy benzene berserk biocide " +
    "biology biomass biotech biotite biozone blister bohemia brendan bronchi broncho " +
    "cadaver carbone cardiac caribou caustic cerebri chamber charter chloral circuit " +
    "clumber cochlea colitis colloid colonel colonic combust condemn conduit contain " +
    "cranial crawler crawley creeper crevice cryogen cryonic culture current degener " +
    "density descent diethyl diffuse dinitro dissect distill dribble dubious electro " +
    "embryol empathy endorse enology environ enzymic espinal eugenic excreta excrete " +
    "exhaust febrile femoral ferment fissure flicker genesis genetic genomic geology " +
    "grendel gristle growler hepatic hideous hisself hormone hydrops hydrous hydroxy " +
    "ileitis immunol incisor inertia infuser inhibit inocula ioniser ionizer isolate " +
    "isotope isotopy jocular ketosis macabre maulana maxilla meiosis meiotic microbe " +
    "mineral mitosis monomer morgana mutatis mutator mycosis mycotic myocyte nephron " +
    "neuroma neurone neutral nitrate nitride nitrile nitrite nitroso nitrous nuclear " +
    "nucleic nucleon nucleus obscura obscure ominous orbital organdy organic organon " +
    "organum organza osmotic osteoid osteoma oxidize peptide phospho pipette plumber " +
    "plummet plunger polymer predate prendre protein quarter reactor reagent retinal " +
    "retinol retinue rupture scalpel screech scuttle secreta secrete secreto seismic " +
    "seizure sendoff sensory shadowy shudder sinuses slither slumber smarter smolder " +
    "smother soluble solvent splenic stagger stalker starter sterile sternal stimuli " +
    "sublime sulfate sulfide sulfite sulfone sulphur surgeon surgery symptom synapse " +
    "tactile thermal thissen thyroid titrate torment toxemia toxicol toxicon trachea " +
    "tremble turbine twitchy tympani ufology uniform upsurge uptrend uveitis vaccine " +
    "vicious viremia viruses viscera viscose voltage yearend zionism zionist"
  ).split(' ');

  BY_LENGTH[8] = (
    "aberrant abrasion abrasive academia acidemia acidosis affright agenesis alderman alkalies " +
    "alkaline alkaloid alveolar ammonite ammonium amputate anabolic analysis analytic antibody " +
    "antidote arguendo arterial arteries atrophic auricula bacteria bailment basaltic behemoth " +
    "bioassay biocidal biogenic biologic biometry biopsies bronchus bulkhead bursitis busulfan " +
    "cannibal carbonic carbonyl cardigan cardinal cardioid carnival catalyse catalyst cerebral " +
    "cerebrum chlorate chloride chlorine chlorite classify clavicle clinical cochlear coenzyme " +
    "coliform collapse colonial colonies colonise colonist colonize comatose comprend condense " +
    "convulse corridor cortical cortices creepier cryolite cryostat cyanosis cystitis cytology " +
    "cytosine delirium dendrite derelict desolate devourer diagnose dialysis diffuser digester " +
    "dilution dilutive dimethyl disaster disulfid doxology dreadful duodenal duodenum ectoderm " +
    "electric electron embalmer emergent emulsify emulsion endoderm endorser endosome epidemic " +
    "ethylene etiology euphemia evacuate excavate excision exotoxin facility fibrosis filiform " +
    "filtrate follicle forsaken fracture fribourg frighten fungible fusiform ganglion gangrene " +
    "geologic geometer geometry glycemia grottoes hematite hematoma hepatica hepatoma homology " +
    "hormonal hydrogel hydrogen hydronic hydrosol hydroxyl hypnosis immunize incision incisive " +
    "incubate indology inertial infector infusion injector innuendo inoculum ischemia ischemic " +
    "isogenic isolator isometry isotopic jatropha kurtosis kyphosis languish leucemia leukosis " +
    "lobotomy lordosis lymphoid lymphoma lysosome lysozyme mastitis mechanic membrane mesoderm " +
    "microbus molecule monocyte mortuary motorcar motorist motorman motorway muscular musculus " +
    "mutation mycology myelitis myoblast myogenic myopathy myositis myosotis myotonia myotonic " +
    "myxedema narcotic narendra necropsy necrosis necrotic neoplasm nephrite neuritis neuronal " +
    "neuropil neuroses neurosis neurotic nitrogen nocardia nontoxic nosology nuclease nucleate " +
    "nucleoli oblivion odometer omniform oncology orchitis organise organism organist organize " +
    "orogenic orthosis osteitis oxidizer palliate pancreas pandemic paralyse paralyze parasite " +
    "parterre pathogen peroxide phimosis phosphor platelet poisoner poxvirus predator promotor " +
    "prophage protocol proviral provirus pustular pyoderma pyogenic ravenous reactive receptor " +
    "redactor reflexes renderer reovirus restrict retinoid reverend rheology rhinitis ribosome " +
    "saturate savagery schemata screamer scrubber secretin sedation sedative sediment serology " +
    "sinister sinusoid skeletal skeleton slithery specimen splendid splendor stenosis stimulus " +
    "submerge sufferer sulfonic sulfonyl sulfuric sulphate sulphide sulphite surgical suspense " +
    "symbiont sympathy synapsis syndrome taxonomy teaberry tectonic thematic theology thoracic " +
    "throttle tibialis topology tormenta toxicant toxicity tracheal tympanic tympanum unionism " +
    "unionist unionize unstable ureteral ureteric vaccinia vagotomy vascular venomous vertebra " +
    "virology virulent visceral vivisect volatile zoonosis zoonotic"
  ).split(' ');

  BY_LENGTH[9] = (
    "abdominal abscesses abyssinia accademia adipocyte adrenalin aetiology aflatoxin agonistic alkalosis " +
    "anabolism anaplasma anhydride anhydrite anhydrous anomalies anomalous antigenic antipathy antiserum " +
    "antitoxin antivenom antiviral antivirus apologist apparatus arbovirus arteritis arthritis arthrosis " +
    "asplenium astrocyte astrology atrophied auricular autogenic autolysis autopsied autopsies avascular " +
    "avirulent bacterial bacteriol bacterium barometer beanstalk berserker binocular biography biohazard " +
    "biologist biometric biosensor biosphere bisulfite bolometer bonderman bronchial cadaveric calcified " +
    "capillary carabidae carbonado carbonate carbonite carnivora carnivore cartilage catabolic catalysis " +
    "catalytic cavernous charterer chemostat chlordane chlorella chlorosis chlorotic chromogen circuitry " +
    "circulate cirrhosis clarendon clinician coagulant coagulase coagulate colectomy colloidal colonizer " +
    "colonnade combustor condenser contagion container contusion copolymer cornstalk corrosion corrosive " +
    "cosmology crescendo crosstalk cruciform cryogenic cuneiform cytokinin cytologic cytolysis cytolytic " +
    "cytometer cytoplasm cytotoxic cytotoxin decompose deferment delirious dendritic diagnosis dichotomy " +
    "diffusion diffusive digestion digestive dihydroxy dinitrate dipeptide disinfect dissector distiller " +
    "disulfide downtrend dunstable durometer dysplasia dystrophy echovirus ecologist ectoplasm edematous " +
    "electrode embryonal embryonic emergence emergency encaustic endocrine endocytic endophyte endorphin " +
    "endoscope endoscopy endosperm endotoxin endowment enteritis enzymatic epidermal equipment ergometer " +
    "erogenous erythroid esophagus etymology euthyroid evaporate excavator excretion excretory exogenous " +
    "exstrophy fermenter fermentum fluoresce frightful fungicide gastritis gastropod generator genetical " +
    "genocidal geography geologist glandular grotesque gwendolen haematoma halitosis hematuria hemolymph " +
    "hemolysin hemolysis hemolytic hepatitis heterosis histology homicidal hydraulic hydrocele hydrofoil " +
    "hydrolase hydrology hydrolyze hydroxide hyperemia hypoxemia immunogen incubator infection infective " +
    "inhibitor injection injective inoculant inoculate inorganic insoluble insolvent insurgent intestine " +
    "ischaemia ischaemic isoenzyme isolation keratitis keratosis ketogenic kilometer laminitis laryngeal " +
    "leiomyoma lethality leucocyte leukocyte limestone lipolysis lipolytic lobectomy locomotor lumberman " +
    "lumbermen lymphatic lysosomal machinery malignity manometer manometry maxillary mechanism mechanize " +
    "megacolon melungeon metabolic methylase methylene metrology microbeam microbial mitogenic molecular " +
    "monocular monogenic monomeric monstrous morbidity morganite motorbike motorboat motorcade multiform " +
    "museology mutagenic mycotoxin myoclonic myoclonus myoglobin nanometer necrology neoplasia nephritis " +
    "nephrosis nephrotic neuralgia neuroglia neurology nitration nonlethal nucleolar nucleolus obscurity " +
    "olfaction olfactory oncogenic oogenesis optometry organelle organizer organotin orography osteology " +
    "osteopath osteotomy oxygenase oxygenate pachyderm paralysis paralytic parasitic pathology pedometer " +
    "peptidase perdition perforate petrology phagocyte philology phlebitis phosphate phosphide phosphine " +
    "phosphite pituitary plexiform pneumatic poisonous polygenic polymeric polyposis preceptor predation " +
    "predatory proctitis prognosis psychoses psychosis pulmonary pyrolysis pyrolytic pyrometer radiology " +
    "recurrent redaction referenda reflexion reflexive regenesis rendement rendition resolvent resurgent " +
    "retinitis rheometer ribosomal ricardian sandblast schematic sclerosis scoliosis sebaceous secretary " +
    "secretion secretive secretory semicolon semiology serologic shadowbox silicosis sinusitis sociology " +
    "spasmodic spiderman splendour sterilise sterility sterilize stimulant stimulate stonecrop structure " +
    "sublethal sublimate sublimity sulfatase sulfation sulfonate sulfoxide sulfurous sulphuric surgeries " +
    "surrender symbiosis synovitis syntheses synthesis taxonomic tecnology telepathy terrorise terrorism " +
    "terrorist terrorize thymocyte titration tonometry tormentor toxicosis toxigenic traumatic tribology " +
    "trichloro trimethyl tularemia tunnelled urography urologist vaccinate vaccinium vaginitis vasectomy " +
    "vasomotor vasospasm ventilate vertebrae vertebral virologic virulence viscosity xeroderma zoologist " +
    "zoophilia"
  ).split(' ');

  BY_LENGTH[10] = (
    "aberration abyssinian acanthosis acrophobia actomyosin adenopathy adenoviral adenovirus adrenaline affliction " +
    "aldermanic alkalinity allergenic alveolitis ammoniacal amphibious amputation analytical analytique androgenic " +
    "anemometer anesthesia anesthetic angiogenic antagonism antagonist antagonize antibodies antifungal antiseptic " +
    "anxiolytic apiculture apotheosis arteriolar asbestosis astrometry atraumatic audiometer audiometry autogenous " +
    "babesiosis bacteremia bedchamber biochemist biocontrol biodynamic biogenesis biographer biological biomorphic " +
    "blastoderm bronchitis cadaverous calcinosis carbondale carbonless cardinalis cardiology catabolism catabolite " +
    "cellulitis centrifuge cervicitis chambertin chinaberry chloramine chloroform chromosome chronology circuitous " +
    "circulator classified classifier classifies clinometer colposcopy combustion commutator compressor concentric " +
    "conchology concurrent condensate conferment contagious convulsion convulsive cosmogenic craniotomy crawlspace " +
    "cretaceous cryosphere crystallin curvaceous cystectomy cystinosis cystoscopy cytochrome cytopathic cytostatic " +
    "declassify degeneracy degenerate demography demonology derailment dermaptera dermatitis dermatoses desolation " +
    "diagenesis diagenetic diagnostic dichloride dichlorvos dielectric diffusible digestible dihydrogen dissection " +
    "distillate distillery disulfiram disulfoton disulphide dreadlocks dysgenesis echinoderm ectodermal electrical " +
    "electronic embryology emulsified emulsifier endodermal endodontic endogenous endoscopic endosulfan entailment " +
    "entomology enviroment enzymology epicardial epigenetic episiotomy epithermal esophageal estrogenic eubacteria " +
    "evacuation evaporator eviscerate excavation exhaustion exhaustive exhumation exobiology exocytosis fathomless " +
    "fibroblast filtration follicular foreshadow foundation fungicidal futurology ganglionic gangrenous gastronome " +
    "gastronomy gastropoda gemologist geneticist geological geothermal germicidal gingivitis glaciology glycolipid " +
    "glycolysis glycolytic goniometer haemolysis haemolytic halocarbon hematocrit hematology hemocyanin hemoglobin " +
    "hemophilia hemoptysis hemorrhage hemorrhoid hemostasis hemostatic hepatocyte hepatology heptachlor herbaceous " +
    "histologic holoenzyme holography homeopathy homogenous homophobia horrendous hydrograph hydrologic hydrolysis " +
    "hydrolytic hydrometer hydrophone hydroplane hydroponic hydropower hydroxamic hygrometer hypoplasia iatrogenic " +
    "ichthyosis iliotibial immunology implacable incinerate incubation inexorable infectious infiltrate inhibition " +
    "inhibitory injectable innuendoes instrument insurgence insurgency intestinal intoxicant intoxicate ionisation " +
    "ionization iridescent isothermal jocularity keratotomy laboratory laceration languishes laparotomy laryngitis " +
    "leukopenia lumberjack lumberyard lumpectomy lymphedema lymphocyte macrophage malevolent mandibular mastectomy " +
    "mathematic mechanical melanocyte membranous meningitis mesodermal metabolism metabolite metabolize metaplasia " +
    "methyldopa microbiota micrometer microscope microscopy mineralogy monoclinic monomethyl montrachet morphology " +
    "mortuaries motoneuron motorcoach motorcycle mutational mycoplasma mycorrhiza myelopathy myocardial myocardium " +
    "myogenesis myomectomy myometrium myopathies necromancy necromania nematology nephrology neuroblast neurogenic " +
    "neurologic neuropathy neuroptera neurospora neurotoxic neurotoxin neutralise neutrality neutralize nonaqueous " +
    "noncurrent nonthermal nonuniform novobiocin nucleation nucleoside nucleotide oceanology ochratoxin oculomotor " +
    "oesophagus omnivorous oncologist organismal organismic osteoblast osteoclast osteogenic osteolysis osteopathy " +
    "overshadow oxygenator palliation palliative palynology pancreatic pancreatin parasitica parasitism parasitoid " +
    "passionist pathogenic pathologic pedophilia perchloric perforator peroxidase persulfate pesticidal phagocytic " +
    "pharyngeal phlebotomy phosphagen phosphatic phosphonic phosphoric phosphorus phosphoryl photogenic photolysis " +
    "photometer photometry phytogenic picrotoxin poisonwood poliovirus polyclinic polymerase polymerize precipitin " +
    "preferment pressurize prognostic proteinase protoplasm psychology pulmonaria putrescine pyrography quarantine " +
    "quarterman radiogenic radiograph radiologic radiolysis radiometer radiometry radiopaque reactivate reactivity " +
    "reanalysis reclassify referendum relentless rendezvous reorganise reorganize respirator resurgence rhinovirus " +
    "riboflavin saturation secretaire seismicity septicemia servomotor sexologist shadowland sinusoidal sonography " +
    "speleology spirometer spirometry spongiform stalactite stalagmite steriliser sterilizer stimulator stomatitis " +
    "stratiform structural stupendous subculture subliminal suborbital subsurface sufferance sulfhydryl superoxide " +
    "suspension synephrine synthesise synthesize tachometer taxonomies technology tendinitis tendonitis terrorizer " +
    "tetraethyl tetrahydro thymectomy tomography tonsilitis topography toxicities toxicology toxoplasma tremendous " +
    "trinitrate trinocular tripeptide tunnelling typography ulceration ulcerative unbuffered uninfected urethritis " +
    "urinalysis vasculitis venography ventilator vertebrata vertebrate virologist viscometer vivisector volatility " +
    "xenophobia"
  ).split(' ');

  BY_LENGTH[11] = (
    "abandonment abiogenesis abortionist agoraphobia agriculture allelopathy amyloidosis amyotrophic anaesthesia anaesthetic " +
    "analyticity anastomosis anesthetist angiography antechamber antithyroid apparatuses aquaculture arabidopsis archaeology " +
    "arthropathy astrocytoma atherogenic audiologist bacteraemia bacteriocin bacteriuria bicarbonate bimolecular biochemical " +
    "bioelectric biographies biomaterial biophysical biorhythmic blasphemous blepharitis bradycardia bronchiolar brucellosis " +
    "cannibalism cannibalize capillaries carbonation cardinality cardiogenic cardiotonic carnivorous cartography catastrophe " +
    "centrifugal chamberlain chambermaid chemosphere chemotactic chlorinator chlorophyll chloroplast chloroquine cholangitis " +
    "chondrocyte christendom chromogenic chromophore chromosomal chronometer circulation circulatory climatology coagulation " +
    "coccidiosis collapsable collapsible colonialism colonialist colonoscopy combustible commutation commutative concentrate " +
    "containment contaminant contaminate coprophilia coronavirus corrosivity creationism creationist criminology cryobiology " +
    "cryosurgery cryotherapy crystalline crystallise crystallite crystallize curtailment cytogenetic cytokinesis cytological " +
    "cytoplasmic demonstrate deoxyribose depredation dereliction dermatology diagnosable diffusional diffusivity dipeptidase " +
    "diphosphate discography dreadnaught dreadnought dynamometer electrician electricity electrocute electroless electrology " +
    "electrolyte embryophyta emergencies endocardial endocytosis endodontist endometrial endometrium endoplasmic endorsement " +
    "endothelial endothelium endothermic enteropathy enterotoxin enterovirus enucleation environment epinephrine erythrocyte " +
    "esophagitis ethnography ethnologist evaporation evaporative exhaustible exonuclease exoskeleton extraocular fermentable " +
    "filmography flexography fluorescein fluorescent fluorogenic fluorometer fluorometry fluoroscopy ganglioside gastrectomy " +
    "gastronomic gastroscopy gastrostomy goaltending godforsaken granulocyte gynaecology haematocrit haematology haemoglobin " +
    "haemophilia haemorrhage haemostasis hagiography headquarter hematologic hematoxylin hemodynamic hemopoietic hemorrhagic " +
    "hepatectomy hepatotoxic herbivorous herpesvirus heterogenic histoplasma homeostasis homoeopathy homopolymer hydrocarbon " +
    "hydrogenase hydrography hydrologist hydrolysate hydrometric hydrophilic hydrophobia hydrophobic hydrosphere hydrostatic " +
    "hydroxylase hydroxyurea hydroxyzine hyperplasia hypertrophy hypokalemia hypothyroid ichthyology iconography illusionist " +
    "immunoassay immunogenic immunologic imperforate incinerator indigestion infectivity infiltrator inflammable inoculation " +
    "intercostal interneuron intradermal intraocular intravenous isoelectric keratectomy laminectomy laparoscopy laryngology " +
    "lipogenesis lipoprotein listeriosis lithography luminescent lymphoblast lymphocytic lymphoedema lymphotoxin machineries " +
    "malevolence mammography mariculture mechanistic meteorology methylamine methylation microbicide micronuclei microscopic " +
    "monoculture mononitrate mononuclear monstrosity morbidities morphometry muscularity musculature muskellunge mutagenesis " +
    "mycological mycorrhizae mycorrhizal myelination myelogenous myelography myocarditis myxomatosis naturopathy necromancer " +
    "necromantic necrophagia necrophilia neocortical neonatology nephrectomy nephrogenic nephropathy nephrotoxic neuroactive " +
    "neuroleptic neurologist neuropathic neuroticism neutralizer nitrogenous nitrophenol nonclinical nonreactive nonsurgical " +
    "nonvolatile nucleophile nucleoplasm obscuration obscurities odontogenic oesophageal oncogenesis ontogenetic orchiectomy " +
    "orthography osteopathic ovariectomy overcurrent overvoltage oxychloride oxygenation paedophilia paleography pandemonium " +
    "papilledema parasitemia parathyroid pathologies pathologist pentecostal perchlorate perforation pericardial pericardium " +
    "perinuclear peritonitis permutation petrography pharyngitis philologist phosphatase phosphonate phosphorous photography " +
    "photophobia phytologist plantagenet pneumonitis polynuclear polypeptide polysorbate pornography precipitate precipitous " +
    "preclinical primatology prostatitis protagonist proteinuria proteolysis proteolytic psittacosis psychogenic psychometry " +
    "psychomotor psychopathy quarterback quarterdeck radioactive radiocarbon radiography radiologist recirculate rediffusion " +
    "reemergence reflexivity reflexology regenerator reinfection remembrance remonstrate respiration respiratory resplendent " +
    "restriction restrictive restructure resynthesis retinopathy revisionism revisionist ribonucleic sarcoidosis scenography " +
    "scleroderma scuttlebutt secretarial secretariat secretaries sedimentary seismometer septicaemia serendipity sericulture " +
    "serological slumberland sociologist soteriology spectrogram speedometer spermicidal splenectomy spondylitis spondylosis " +
    "stenography stimulation stimulative stimulatory subclinical subcortical sublimation submergence sulfonamide suppuration " +
    "suppurative suspenseful symptomatic symptomless synthesizer tachycardia teleseismic teratogenic terminology terroristic " +
    "tetramethyl thalassemia therapeutic thermogenic thermometer thermometry thiosulfate thoracotomy thyroiditis tonsillitis " +
    "toxicologic tracheotomy transfusion translucent trichinosis trichloride trichoderma trophoblast tropomyosin tumorigenic " +
    "unchartered underground undermanned undiagnosed unfermented uninhibited unorganised unorganized vaccination vascularity " +
    "vasculature ventilation ventilatory virological viscosities viticulture vivisection volcanology woodcreeper"
  ).split(' ');

  BY_LENGTH[12] = (
    "abolitionism abolitionist accordionist acetonitrile adenoviruses aminobenzoic aminocaproic anaerobiosis anaesthetist androgenetic " +
    "angiogenesis antagonistic antigenicity antiplatelet appendectomy appendicitis archeologist arthrography astrobiology asymptomatic " +
    "autoantibody bactericidal bacteriology baroreceptor bibliography biochemistry biogeography biomechanics biosynthesis biosynthetic " +
    "bronchogenic bronchoscopy bronchospasm carbonaceous cardiologist cardioplegia catastrophic charterhouse chlorambucil chlorination " +
    "chlorophenol chloropicrin choreography chromatogram chromosphere classifiable collaborator colonisation colonization concentrator " +
    "condemnation condensation craniofacial craniosacral cryptography cyberculture cytochalasin cytochemical cytotoxicity declassified " +
    "decomposable degeneracies degeneration degenerative demonstrable demonstrator densitometer densitometry dermabrasion dermatologic " +
    "desaturation detoxication diatomaceous diethylamide dinucleotide disinfectant disinfection distillation distilleries ecclesiology " +
    "egyptologist electrograph electrolysis electrolytic electrometer electroplate electroshock ellipsometry emulsifiable encephalitis " +
    "endocarditis endocervical endometritis endomorphism endonuclease endotracheal entomologist eosinophilia epidemiology epididymitis " +
    "epiglottitis epileptiform erythematous erythromycin ethylbenzene evisceration evolutionism evolutionist expansionism expansionist " +
    "extracranial extrahepatic extrasensory fermentation fermentative fibrinolysis fibrinolytic flavoprotein floriculture fluorescence " +
    "fluorocarbon folliculitis foundational galactosemia galvanometer gastroplasty geomechanics glaucomatous glycopeptide glycoprotein " +
    "gynecologist haemodynamic haemorrhagic heartrending hematologist hemodialysis hemorrhoidal heterogenous hidradenitis histogenesis " +
    "histological horticulture hydatidiform hydrobiology hydrobromide hydrochloric hydrocolloid hydrodynamic hydrofluoric hydroforming " +
    "hydrogeology hydrographic hydrological hydromassage hydroquinone hydrotherapy hydrothermal hyperkalemia hyperthyroid hypertrophic " +
    "hypocalcemia hypochlorite hypoglycemia hyponatremia hysterectomy immunisation immunization immunologist incandescent incineration " +
    "inclinometer indigestible indissoluble infiltration infiltrative inflammation inflammatory insecticidal installation instrumental " +
    "insufferable insurgencies intoxication intracardiac intracranial intrahepatic intranuclear intuitionism invertebrate isolationism " +
    "isolationist laboratories laryngectomy laryngoscope laryngoscopy leukocytosis lexicography luminescence lymphangioma macronuclear " +
    "magnetometer malignancies mathematical methoxychlor microbalance microbiology microcircuit micronucleus microsurgery mineralogist " +
    "misdiagnosis mitochondria motorcyclist motorization multisensory musicologist mycobacteria nephelometer nephrologist neuroanatomy " +
    "neurobiology neurogenesis neurological neuroscience neurosurgeon neurosurgery neurotrophic nitroaniline nitrobenzene nitromethane " +
    "nitrosomonas nonmalignant nucleocapsid nucleophilic nucleotidase nutritionist obscurantism obscurantist oceanography oophorectomy " +
    "opthalmology organisation organization organoleptic osteoblastic osteogenesis osteomalacia osteoporosis osteoporotic osteosarcoma " +
    "otosclerosis palaeography paleontology pancreatitis parasitology pathobiology pathogenetic pathological penetrometer pentapeptide " +
    "pericarditis perivascular peroxidation petrogenesis phagocytosis phosphatidic phosphatidyl phospholipid photobiology photocurrent " +
    "photopolymer phylogenetic physiography physiologist plasmacytoma polycythemia polyethylene polymyositis postcolonial postsurgical " +
    "precipitable precipitator preemergence premalignant psychologist psychosexual psychosocial psychrometer putrefaction pyroelectric " +
    "quarterfinal quarterlight quarterstaff radiobiology radiographer radiographic radioisotope radiological radiosurgery reactivation " +
    "reactivities receptionist reclassified reductionism reductionist remonstrance resuspension reticulocyte ribonuclease secessionist " +
    "secretagogue seismologist semivolatile sensorimotor silviculture siphonaptera sociobiology spectrograph spectrometer spectrometry " +
    "spectroscope spectroscopy stapedectomy substructure subterranean sulfadiazine sulfonylurea supranuclear technologist tetrodotoxin " +
    "thermography thoracoscopy thrombolysis thrombolytic toxicologist tracheostomy translucence translucency traumatology tribological " +
    "trigonometry triphosphate tuberculosis uncirculated unclassified undercurrent undervoltage unfathomable unionization unmethylated " +
    "unrestricted unsaturation unstimulated unstructured unvaccinated volatilities zoogeography"
  ).split(' ');

  BY_LENGTH[13] = (
    "accelerometer acetaminophen acrylonitrile actinomycosis adenoidectomy adrenalectomy agrobacterium aminophylline anacardiaceae anthropogenic " +
    "anthropometry antibacterial anticoagulant antimicrobial antispasmodic arachnoiditis arboriculture archaeologist architectonic arteriography " +
    "arteriovenous aspergillosis atherogenesis autobiography autocatalytic bacteriophage bioelectrical biogeographic biomechanical biopsychology " +
    "biotechnology blastomycosis blepharospasm bronchiolitis calcification cannibalistic carboniferous cardinalities cardiographer carnivalesque " +
    "cartilaginous catastrophism cerebrospinal chlorhexidine chlorobenzene chloromethane chlorophyceae cholecystitis chromatograph chromospheric " +
    "climatologist commutativity concentration concentricity connectionism contamination contortionist corticospinal corticotropin cosmetologist " +
    "criminologist cryptanalysis crystallinity cytochemistry cytopathology decomposition decontaminate dehydrogenase demethylation demonstration " +
    "demonstrative demyelination dermatologist desulfovibrio diagnostician digestibility dimethylamine dimethylamino dinitrophenol disinhibition " +
    "echinodermata electrocution electrologist electromagnet electromotive electrophilic electrostatic embryogenesis embryological endobronchial " +
    "endocrinology endometriosis endopeptidase endopterygota enterocolitis environmental epicondylitis epidemiologic epidermolysis exhibitionism " +
    "exhibitionist expressionism expressionist extravascular ferroelectric foraminiferal fusobacterium gastrocnemius gastronomical gastroparesis " +
    "gastroschisis geochronology gerontologist gynaecologist haemodialysis hematological hematopoiesis hematopoietic heteronuclear hydroacoustic " +
    "hydrochloride hydroelectric hydrogenation hydrogeologic hydroperoxide hydroxylamine hydroxylation hypercalcemia hyperglycemia hyperhidrosis " +
    "hypertrophied hyperuricemia hypoglycaemia immunological immunotherapy impressionism impressionist incandescence inexhaustible insectivorous " +
    "intracerebral intramuscular intrathoracic intratracheal intravascular lagerstroemia leptospirosis lipodystrophy longsuffering lymphadenitis " +
    "lymphoblastic macromolecule mathematician maxillofacial mechanization megakaryocyte metallography meteorologist methemoglobin methylparaben " +
    "microanalysis microbiologic microorganism microscopical microsurgical mineralogical misclassified mitochondrial mitochondrion monochromator " +
    "mononucleosis monstrosities morphogenesis morphogenetic mycobacterial mycobacterium myelofibrosis neuroblastoma neurochemical neuromuscular " +
    "neurosurgical neurosyphilis neurotoxicity neurovascular nitrification nitroglycerin nitroprusside nonclassified noncondensing nondegenerate " +
    "noninfectious nonpathogenic nonstructural noradrenaline nucleoprotein onychomycosis ophthalmology organogenesis ornithologist oropharyngeal " +
    "osteomyelitis osteonecrosis osteopetrosis palaeontology pathogenicity peptidoglycan percussionist perfectionism perfectionist periodontitis " +
    "phosphokinase phospholipase phosphorylase phosphorylate photoelectric photoelectron photoreceptor phytotoxicity piezoelectric pneumonectomy " +
    "poliomyelitis polyarteritis polyarthritis polycarbonate postemergence posttraumatic potentiometer precipitation projectionist prostatectomy " +
    "protectionism protectionist proteinaceous pseudoobscura psychosomatic psychosurgery pyrophosphate quartermaster radioactivity recirculation " +
    "reflectometer reflectometry reflexologist refractometer revolutionise revolutionist revolutionize salmonellosis scientologist sedimentation " +
    "sedimentology sensorineural serendipitous serodiagnosis sigmoidoscopy somatosensory spectrometric spectroscopic sphingomyelin steganography " +
    "sterilization steroidogenic stoichiometry structuralism structuralist structuration submandibular sulfanilamide sulfisoxazole sympathectomy " +
    "tenosynovitis tetrachloride therapeutical thermogenesis thermonuclear thoracolumbar thyroidectomy tonsillectomy toxicodendron toxicological " +
    "toxoplasmosis transmembrane transmutation transthoracic triethylamine trinucleotide"
  ).split(' ');

  BY_LENGTH[14] = (
    "achondroplasia adrenocortical agrobiological aminopeptidase anesthesiology anthropologist anticonvulsant antihemophilic arthrogryposis bacteriologist " +
    "bacteriostatic bioengineering bioluminescent biomathematics bronchiectasis bronchodilator carcinogenesis cardiomyopathy cardiovascular centrifugation " +
    "chlorothiazide chlorpromazine chlorpropamide chromatography cinematography classification classificatory claustrophobia conjunctivitis containerboard " +
    "corticosteroid corticosterone counterculture countercurrent craniocerebral cryptococcosis cytotechnology dechlorination decolonisation decolonization " +
    "dermatological diffractometer dinitrotoluene diverticulitis echinococcosis echocardiogram electrodynamic electrofishing electrokinetic electromedical " +
    "electrosurgery electrotherapy electrothermal emulsification encephalopathy endarterectomy epidemiologist ergocalciferol erythropoiesis erythropoietin " +
    "extrapulmonary flavobacterium gastroduodenal glucocorticoid granulomatosis haematological haematopoietic hallucinogenic hemoglobinuria hepatocellular " +
    "hepatotoxicity histopathology histoplasmosis historiography hydrocortisone hydrodynamical hydrogeologist hydronephrosis hydrophobicity hydroxyapatite " +
    "hydroxyproline hyperglycaemia hyperkeratosis hyperlipidemia hypersecretion hypopharyngeal hypophysectomy hypothyroidism immunochemical immunogenicity " +
    "immunoglobulin immunoreactive indecomposable infrastructure interactionism interferometer interferometry intermolecular intervertebral intramolecular " +
    "intuitionistic leiomyosarcoma leukodystrophy macromolecular metapsychology microbiologist microelectrode microinjection micromechanics microstructure " +
    "mineralization nasopharyngeal nephrotoxicity neurochemistry neuroendocrine neuropathology neuroscientist neurosecretory neutralization nitrocellulose " +
    "nitroglycerine noncombustible noncommutative nonradioactive norepinephrine obstructionism obstructionist ophthalmoscopy optoelectronic organisational " +
    "organizational organochlorine organometallic orthomolecular orthophosphate osteoarthritic osteoarthritis osteodystrophy osteosynthesis otolaryngology " +
    "paleogeography paleontologist pancreatectomy patellofemoral pentecostalism periodontology pharmacologist phosphoprotein phosphorescent photobacterium " +
    "photocatalytic photosynthesis phytopathology plasmapheresis pneumoconiosis polymerization polyneuropathy polynucleotide pressurization prognosticator " +
    "prohibitionist psychoanalysis psychoanalytic pyelonephritis recolonization reinstallation reorganization retinoblastoma rheumatologist ribonucleoside " +
    "ribonucleotide segregationist spectrographic spectroscopies sphincterotomy superinfection superphosphate superstructure supramolecular symptomatology " +
    "thermalization thermoelectric thyrotoxicosis trimethylamine ultrastructure unclassifiable undersecretary volatilization"
  ).split(' ');

  BY_LENGTH[15] = (
    "agranulocytosis anaesthesiology anticoagulation atherosclerosis autoradiography bacteriological bioaccumulation bioavailability biogeographical bioluminescence " +
    "biostratigraphy bronchoalveolar cannibalization cardiopulmonary cerebrovascular chloramphenicol cholangiography cholecalciferol cholecystectomy chromatographic " +
    "chromobacterium conservationist constructionism constructionist corynebacterium crystallisation crystallization crystallography cytomegalovirus deconcentration " +
    "decontamination dehydrogenation denitrification desulfurization dichlorobenzene dichloromethane dihydrochloride disorganization electroacoustic electrochemical " +
    "electromagnetic electronegative electrophoresis electrophoretic electrosurgical endocrinologist epichlorohydrin epidemiological ethylenediamine expressionistic " +
    "gastroenteritis gluconeogenesis hemochromatosis heterostructure histopathologic hydrogeological hyperthyroidism hypopituitarism immunochemistry immunodiffusion " +
    "immunopathology impressionistic instrumentalist instrumentality instrumentation interlaboratory interphalangeal interventionism interventionist lymphadenopathy " +
    "lymphogranuloma methylphenidate microbiological microdissection microelectronic microstructural musculoskeletal neuroanatomical neurobiological neurofibrillary " +
    "neurophysiology neuropsychiatry neuropsychology nucleosynthesis oligonucleotide ophthalmologist organophosphate osteochondritis palaeogeography parthenogenesis " +
    "pathomorphology pathophysiology phosphocreatine phosphorescence phosphorylation photoionization physiopathology plethysmography polycrystalline polyelectrolyte " +
    "preinstallation preservationist prognostication psychopathology quarterfinalist spermatogenesis steroidogenesis supersaturation sympathomimetic tetrahydrofuran " +
    "thalamocortical trichloroacetic trichloroethane trinitrotoluene ultrafiltration ultrasonography ultrastructural vascularization"
  ).split(' ');

  BY_LENGTH[16] = (
    "aminotransferase anesthesiologist antiinflammatory arteriosclerosis astrophotography autobiographical autofluorescence autoradiographic bioenvironmental bronchopneumonia " +
    "bronchopulmonary carboxypeptidase chemiluminescent chemoprophylaxis chemotherapeutic chlordiazepoxide chlorpheniramine containerization copolymerization counterterrorism " +
    "counterterrorist crystallographic cyclophosphamide declassification demineralization dendrochronology deoxyribonucleic depolymerization dermatopathology dihydroxyacetone " +
    "electrochemistry electrohydraulic electromagnetism electromyography electrotechnical enteropathogenic environmentalism environmentalist erythroblastosis extrachromosomal " +
    "gastroenterology gastroesophageal gastrointestinal glossopharyngeal hydroelectricity hyperventilation immunoreactivity microcirculation microcrystalline microenvironment " +
    "neuropsychiatric neurotransmitter organophosphorus otolaryngologist paleoceanography pathophysiologic pheochromocytoma phosphoglycerate photocoagulation photolithography " +
    "photoluminescent photomicrography pseudomembranous psychoanalytical reclassification rhabdomyosarcoma sedimentological sphygmomanometer thrombocytopenia thrombocytopenic " +
    "thrombophlebitis tracheobronchial trimethylbenzene ventriculography"
  ).split(' ');

  var ALL = [];
  for (var L in BY_LENGTH) ALL = ALL.concat(BY_LENGTH[L]);

  CT.WordBank = {
    byLength: BY_LENGTH,
    all: ALL,
    lengths: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    count: 4197
  };
})(typeof window !== 'undefined' ? window : globalThis);
